
using Content.Shared._DVA.Research.Components;
using Content.Shared._DVA.Glimmer;

namespace Content.Shared.Research.Systems;

/// <summary>
/// Handling for Glimmer changes due to research and artifacts.
/// </summary>
public abstract partial class SharedResearchSystem
{
    [Dependency] private DVGlimmerSystem _glimmer = default!;

    public void InitializeGlimmer()
    {
        SubscribeLocalEvent<DVAnalysisConsoleGlimmerComponent, GetGlimmerModifiedResearchEvent>(OnGetGlimmerResearch);
    }

    /// <summary>
    /// Handles when an Analysis console generates research and allows for additional points due to Glimmer.
    /// Optionally allows Glimmer to be increased based on the amount of research generated.
    /// </summary>
    /// <param name="console">The console used for generating the Research points.</param>
    /// <param name="arg">Args for the event.</param>
    private void OnGetGlimmerResearch(Entity<DVAnalysisConsoleGlimmerComponent> console, ref GetGlimmerModifiedResearchEvent arg)
    {
        var normalizedGlimmer = Math.Clamp(_glimmer.Glimmer / (float)_glimmer.MaxGlimmer, 0f, 1f); // Coearce to floating point
        var researchMultiplier = .5f + Math.Clamp(Math.Pow(normalizedGlimmer, 0.5f) + 1.5f * Math.Pow(normalizedGlimmer, 10f), 0f, 2.5f);

        // Any fractional research or glimmer is truncated here
        arg.BonusResearch = (int)(arg.ResearchPoints * researchMultiplier);
        arg.GeneratedGlimmer = (int)(arg.ResearchPoints / console.Comp.ResearchPerGlimmer);

        if (arg.ShouldUpdateGlimmer)
            _glimmer.Glimmer += arg.GeneratedGlimmer;
    }
}

/// <summary>
/// Raised by systems to determine how much bonus research and glimmer is generated
/// when extracting from an artifact.
/// </summary>
/// <param name="researchPoints">The incoming number of points.</param>
/// <param name="updateGlimmer">Whether to update the glimmer from this event.</param>
[ByRefEvent]
public sealed class GetGlimmerModifiedResearchEvent(int researchPoints, bool updateGlimmer = false)
{
    /// <summary>
    /// Whether to update glimmer as a result of this event.
    /// </summary>
    public readonly bool ShouldUpdateGlimmer = updateGlimmer;

    /// <summary>
    /// How many research points have been generated by some event.
    /// This is untouched by the event.
    /// </summary>
    public readonly int ResearchPoints = researchPoints;

    /// <summary>
    /// How many research points are generated after being altered by Glimmer.
    /// This is set by the event handlers.
    /// </summary>
    public int BonusResearch = 0;

    /// <summary>
    /// How many glimmer points would be added if glimmer is updated.
    /// </summary>
    public int GeneratedGlimmer = 0;
}
